### ISSUE TITLE
System Mouse Acceleration Curve

### ISSUE THREAD

**Issue by Buyukcaglar** [KScl/opentyrian2000#10]
Can you please implement following OpenTyrian Commit in here also (if not already done);

[Use System Mouse Acceleration](https://github.com/opentyrian/opentyrian/commit/50ba3629bf114d5615c17c56c03a04a9cbeb6d6f)

Default game mouse acceleration makes gameplay miserable on harder difficulty levels, but when  game respects to system mouse acceleration levels, game becomes much more playable and customizable.

Thanks.

**Comment by KScl** [comment]
We're synced with [opentyrian/master](https://github.com/opentyrian/opentyrian) now; I can see that commit (50ba362) is already present, and Windows builds are made using the latest version of SDL2 (2.30.0, as of this writing), so this should be taken care of already.

**Comment by Buyukcaglar** [comment]
Thank you.
