### ISSUE TITLE
Carrot ship Christmas version has missing transparency

### ISSUE THREAD

**Issue by vallenrod** [KScl/opentyrian2000#17]
When Christmas mode is activated the Carrot Ship (green) has visible rectangle around it.

**Comment by vallenrod** [comment]
![Screenshot 2024-12-13 210841](https://github.com/user-attachments/assets/b24581e8-f852-4ee9-8743-e2da7a5c5206)

**Comment by KScl** [comment]
Duplicate of #8: This is not a bug, Tyrian 2000's data files contain this error.
