### ISSUE TITLE
Feature request: MIDI support

### ISSUE THREAD

**Issue by RavenMacDaddy** [KScl/opentyrian2000#5]
Is it possible to implement MIDI support for the soundtrack akin to the option in the original?

**Comment by KScl** [comment]
Closing in favor of opentyrian#47; I don't have any additional information on how the Loudness sound system works.

If upstream gets MIDI playback support we'll get it too, but until that happens...

**Comment by gobalius** [comment]
https://github.com/stuerp/foo_midi/blob/main/3rdParty/libmidi/MIDIProcessorLDS.cpp
