### ISSUE TITLE
Mouse Support in all menus

### ISSUE THREAD

**Issue by OpenRift412** [KScl/opentyrian2000#6]
A peculiar difference I've noticed between OpenTyrian and the OpenTyrian2000 fork seems to be that OpenTyrian allows you to use the cursor on pretty much every menu in the game, while OpenTyrian2000 only allows it in the same places as the original DOS version release of T2000.

Was this scrapped for accuracy reasons or has it just not been ported over?

**Comment by KScl** [comment]
Upstream did this in 0c06118, which—although it appears to be two years old—was only merged in earlier this year.

I haven't had the opportunity to merge in upstream changes yet; I know at the very least the Mouse Settings menu introduced in T2K needs to be updated to match.

**Comment by KScl** [comment]
Fixed by 132e8b4.
