### ISSUE TITLE
[Suggestion] Rename 'OpenTyrian2000' Menu option to 'Setup'

### ISSUE THREAD

**Issue by OpenRift412** [KScl/opentyrian2000#7]
This is probably just an OCD thing, but it just seems a little weird to have the OpenTyrian-specific settings just labelled as 'OpenTyrian2000' instead of something more informative like 'Settings' or 'Setup'. In my opinion it gives the impression that it's more of just an about screen than a menu with additional settings.

Thoughts?

**Comment by KScl** [comment]
Relevant issue: opentyrian#51

I'm not sure I actually agree with this, as "Setup" doesn't really indicate that options _specifically related to OpenTyrian2000_ are to be found there. "OT2K Setup" may be better.

**Comment by OpenRift412** [comment]
> Relevant issue: [opentyrian#51](https://github.com/opentyrian/opentyrian/issues/51)
> 
> I'm not sure I actually agree with this, as "Setup" doesn't really indicate that options _specifically related to OpenTyrian2000_ are to be found there. "OT2K Setup" may be better.

Well the jukebox is also located there, so I think a more agnostic name would still be appropriate.

**Comment by KScl** [comment]
Fixed by 132e8b4.
